#显示配置
jasypt:
  encryptor:
    password: lvjia_lawfrim
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: lvjia_lawfrim
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: select 1
  main:
    allow-bean-definition-overriding: true
swagger:
  enabled: true
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 50
  netty:
    connection-timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xinou.lawfrim
  global-config:
    id-type: 1
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

app:
  version:
    androidMinVersion: 3
    androidNowVersion: 3
    iosMinVersion: 3
    iosNowVersion: 3
#logging:
#  level:
#    com.xinou.lawfrim.web.mapper: debug
